server:
  port: 8821
spring:
  application:
    name: consumer-client
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8801/eureka
      
login:
  level:
    root: INFO