server:
  port: 8070

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db-1808
    username: root
    password: root

mybatis:
  typeAliasesPackage: com.just.pojo
  mapperLocations: classpath:mappers/*.xml

logging:
  level: 
    com.tedu.mapper: debug
